# image will be published to ghcr.io/sernik-tech/<name>
name: mazurek
# description will be included in the image's metadata
description: sneexy's personal hyprland spin

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # installs system related packages
  - from-file: common/sneexy/mazurek/system.yml

  # installs user/userspace related packages
  - from-file: common/sneexy/mazurek/user.yml

  # run scripts afterwards
  - type: script
    scripts:
        - system-mazurek.sh
        - catppuccin-mazurek.sh

  # put some files in the image
  - from-file: common/sneexy/mazurek/files.yml

  # enable systemd units
  - type: systemd
    system:
      enabled:
        - create-sddm-user.service
    user:
      enabled:
        - theme-maintenance.timer
      disabled:
        - theme-maintenance.service

  # installs default repositories and flatpak packages
  - from-file: common/sneexy/mazurek/flatpaks.yml

  # configure what to pull in from ublue-os/bling
  - from-file: common/sneexy/bling.yml

  # install fonts
  - from-file: common/sneexy/fonts.yml

  # GTK settings overrides
  - type: gschema-overrides
    include:
      - zz1-mazurek.gschema.override

  # uBlue akmods. includes custom drivers and stuff
  - from-file: common/sneexy/akmods.yml

  # sets up proper policy & signing files
  - type: signing
