# image will be published to ghcr.io/sernik-tech/<name>
name: wuzetka
# description will be included in the image's metadata
description: sneexy's personal and opinionated kinoite image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
    - from-file: common/sneexy/wuzetka/rpm-ostree.yml

    - type: script
      scripts:
        - ld.sh
        - system-wuzetka.sh
        #- catppuccin-gtk.sh
        - catppuccin-papirus.sh
        - breezemateria.sh

    - type: files
      files:
        - sernik/usr: /usr
        - sneexy/wuzetka/usr: /usr

    - type: containerfile
      snippets:
        - COPY --from=ghcr.io/sernik-tech/wuzetka-packages /artifacts/usr /usr
        # GTK theme
        - COPY --from=ghcr.io/sernik-tech/themes /artifacts/usr/etc/skel/.local/share/themes/Catppuccin-Mocha-Compact-Green-Dark /usr/etc/skel/.local/share/themes/Catppuccin-Mocha-Compact-Green-Dark
        - COPY --from=ghcr.io/sernik-tech/themes /artifacts/usr/etc/skel/.local/share/themes/Catppuccin-Mocha-Compact-Green-Dark-xhdpi /usr/etc/skel/.local/share/themes/Catppuccin-Mocha-Compact-Green-Dark-xhdpi
        - COPY --from=ghcr.io/sernik-tech/themes /artifacts/usr/etc/skel/.local/share/themes/Catppuccin-Mocha-Compact-Green-Dark-hdpi /usr/etc/skel/.local/share/themes/Catppuccin-Mocha-Compact-Green-Dark-hdpi

    - from-file: common/sneexy/wuzetka/flatpaks.yml
    - from-file: common/sneexy/bling.yml
    - from-file: common/sneexy/fonts.yml

    - type: gschema-overrides
      include:
        - zz1-wuzetka.gschema.override

    #- from-file: common/sneexy/akmods.yml
    - type: signing
