# image will be published to ghcr.io/sernik-tech/<name>
name: wuzetka
# description will be included in the image's metadata
description: sneexy's personal and opinionated kinoite image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: common/sneexy/wuzetka/rpm-ostree.yml

  - type: script
    scripts:
        - ld.sh
        - system-wuzetka.sh

  - type: files
    files:
    	- sneexy/wuzetka/usr: /usr

  - from-file: common/sneexy/wuzetka/flatpaks.yml
  - from-file: common/sneexy/bling.yml
  - from-file: common/sneexy/fonts.yml

  - type: gschema-overrides
    include:
      - zz1-wuzetka.gschema.override

  - from-file: common/sneexy/akmods.yml
  - type: signing
