# image will be published to ghcr.io/sernik-tech/<name>
name: krowki
# - Description -
# Will be included in the image's metadata, can be whatever.
description: gay cats from mexico

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
    # Modules here are sourced from files in `/common/rexogamer` for this specific recipe. If you don't want to rely on
    # modules being outside of this recipe file, you can refer to the documentation (linked above) to see examples.
    # Alternatively, use the `recipe-all.yml` recipe instead of this one if you prefer that.

    # - rpm-ostree -
    # Packages that should be installed on the image. Now, when choosing which packages to install, we recommend
    # that you don't attempt to just add everything. Preferably, use anything else (e.g VSCode) inside of distrobox
    # or use flatpaks whenever possible (both preincluded) as alternatives to installing them. Also take note that
    # packages that attempt to create users or groups *will* cause issues when attempting to create your image, so
    # it's best to just layer them manually on your booted system afterwards if this is the case.
    # Documentation: https://blue-build.org/reference/modules/rpm-ostree/
  - from-file: common/rexogamer/rpm-ostree.yml

    # - Script -
    # Use any bash scripts you created during image creation. These are placed within `./config/scripts' in this repository.
    # The 'ld.sh' script simply fixes a minor issue that does get in the way often.
    # Documentation: https://blue-build.org/reference/modules/script/
  - type: script
    scripts:
      - ld.sh

    # - Files -
    # Determines which files you want to add into the "root" (in heavy air quotes, because it's `/usr/`) of your image.
    # TIP: Use `/usr/etc/skel` to add files you'd want to a users home directory after a user creates their profile.
    # Documentation: https://blue-build.org/reference/modules/files/
  - type: files
    files:
      - rexogamer/usr: /usr

    # - Flatpaks -
    # Flatpaks that will end up being installed out of the box on the system. Feel free to add anything here you'd
    # want to be inside of flatpaks on your system.
    # Documentation: https://blue-build.org/reference/modules/default-flatpaks/
  - from-file: common/rexogamer/flatpaks.yml

    # - Fonts -
    # The fonts module allows you to easily install fonts from both Google Fonts and Nerd Fonts.
    # Documentation: https://blue-build.org/reference/modules/fonts/
  - from-file: common/rexogamer/fonts.yml

    # - Gschema Overrides -
    # Allows you to modify the default settings for a lot of things related to GNOME and GTK.
    # Use this to your advantage to change any defaults on GNOME you'd like.
    # Documentation: https://blue-build.org/reference/modules/gschema-overrides/
  - type: gschema-overrides
    include:
      - zz1-krowki.gschema.override

    # - Akmods -
    # Akmods are a neat thing provided by the blue-build people, they're basically easy-to-install kernel modules.
    # Documentation: https://blue-build.org/reference/modules/akmods/
    #
    # Uncomment below *after* modifying the akmods config as all modules are commented by default.
    # - from-file: common/rexogamer/akmods.yml

    # this sets up the proper policy & signing files for signed images to work fully.
    # in *all* cases, this line should NEVER be touched. leave it here as is. there is no need to modify or remove this.
    # Documentation: https://blue-build.org/reference/modules/signing/
  - type: signing

    # Note that not all modules are listed here. We only added some that are most utilized by most users, but there are a
    # lot more modules that can be utilized.
    # You can find extra modules documented here (this is the first entry of the "modules" list):
    # https://blue-build.org/reference/modules/akmods/
