ARG IMAGE_MAJOR_VERSION=40

# KDE/Kwin Extras/Addons
FROM fedora:${IMAGE_MAJOR_VERSION} as kde-extras

COPY config/scripts/build-scripts /tmp/build-scripts

RUN chmod +x /tmp/build-scripts/kde-extras.sh && \
    /tmp/build-scripts/kde-extras.sh

# Joystickwake
#FROM fedora:${IMAGE_MAJOR_VERSION} as joystickwake
#
#COPY config/scripts/build-scripts /tmp/build-scripts
#
#RUN chmod +x /tmp/build-scripts/joystickwake.sh && \
#    /tmp/build-scripts/joystickwake.sh

# Catppuccin
FROM fedora:${IMAGE_MAJOR_VERSION} as catppuccin

# GTK Theme
COPY config/scripts/build-scripts /tmp/build-scripts

RUN chmod +x /tmp/build-scripts/catppuccin-gtk.sh && \
    /tmp/build-scripts/catppuccin-gtk.sh

# Papirus Icons Repatched
#RUN chmod +x /tmp/build-scripts/catppuccin-papirus.sh && \
#    /tmp/build-scripts/catppuccin-papirus.sh

# Packages built with cargo/rust
FROM fedora:${IMAGE_MAJOR_VERSION} as cargo

COPY config/scripts/build-scripts /tmp/build-scripts

RUN chmod +x /tmp/build-scripts/cargo.sh && \
    /tmp/build-scripts/cargo.sh

# Packages built with go
FROM fedora:${IMAGE_MAJOR_VERSION} as go

COPY config/scripts/build-scripts /tmp/build-scripts

RUN chmod +x /tmp/build-scripts/go.sh && \
    /tmp/build-scripts/go.sh

# Finalize container build
FROM fedora:${IMAGE_MAJOR_VERSION}

RUN mkdir -p /artifacts/usr/etc

COPY --from=go /tmp/go-built/usr /artifacts/usr
COPY --from=cargo /tmp/cargo-built/usr /artifacts/usr
#COPY --from=catppuccin /tmp/catppuccin-papirus/usr /artifacts/usr
COPY --from=catppuccin /tmp/catppuccin-gtk/etc /artifacts/etc
#COPY --from=joystickwake /tmp/joystickwake-built/usr /artifacts/usr
COPY --from=kde-extras /tmp/kde-extras-built/usr /artifacts/usr
