# Module Documentation: https://blue-build.org/reference/modules/default-flatpaks/
# Note that using this module will automatically disable the Fedora flatpak repository and
# uninstall any default Fedora flatpaks, although considering how Not So Great it is, it
# probably won't matter to the end user anyways.
type: default-flatpaks
notify: true # Send notification after install/uninstall is finished (true/false)
system:
  install:
    - org.kde.kclock
    - org.kde.filelight
    - org.kde.kamoso
    - org.kde.kfind
    - org.kde.kweather
    - org.kde.gwenview
    - org.kde.kalk
    - org.kde.okular
    - org.mozilla.firefox
    - org.mozilla.Thunderbird
user:
  repo-name: flathub
  install:
    - chat.revolt.RevoltDesktop
    - com.spotify.Client
    - it.mijorus.gearLever
    - com.obsproject.Studio