# Module Documentation: https://blue-build.org/reference/modules/rpm-ostree/
# Official Fedora packages search: https://packages.fedoraproject.org/
type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/atim/lazygit/repo/fedora-%OS_VERSION%/atim-lazygit-fedora-%OS_VERSION%.repo
  - https://pkgs.tailscale.com/stable/fedora/%OS_VERSION%/tailscale.repo
install:
    # Everything under install will be installed, even if it already is.
  - ark
  - dolphin-plugins
  - kate
  - translate-shell
  - ksystemlog
  - gamemode
  - gamescope
  - mangohud
  - podman
  - podman-compose
  - podman-tui
  - zoxide
  - starship
  - bat
  - pipx
  - gh
  - lazygit
    # foot is the default terminal in sway. Adding here for the sake of that, but you could also just add your own
    # configuration files manually with the `files` module!
remove:
    # Everything under remove will be uninstalled from the image, if the package exists.

    # We remove Firefox because we use the flatpak in favor. Also removing the langpacks
    # to prevent dependency problems.
  - firefox
  - firefox-langpacks
