type: default-flatpaks
notify: true
system:
  repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
  repo-name: flathub
  repo-title: "Flathub (system-wide)"
  install:
    # internet
    - org.mozilla.firefox
    - org.mozilla.Thunderbird

    # office
    - org.libreoffice.LibreOffice
    - md.obsidian.Obsidian

      # utilities
    - com.usebottles.bottles
    - fr.handbrake.ghb
    - org.kde.okteta
    - io.github.seadve.Mousai
    - com.dec05eba.gpu_screen_recorder
    - net.davidotek.pupgui2
    - com.github.Matoking.protontricks

    # system applications
    - org.kde.kclock
    - org.kde.filelight
    - org.kde.kamoso
    - org.kde.kfind
    - org.kde.kweather
    - org.kde.gwenview
    - org.kde.kalk
    - org.kde.okular
    - org.pipewire.Helvum
    - org.gnome.World.PikaBackup
    - com.github.tchx84.Flatseal
    - org.gustavoperedo.FontDownloader
    - io.github.thetumultuousunicornofdarkness.cpu-x
user:
  repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
  repo-name: flathub-user
  repo-title: "Flathub (User)"
  install:
    # internet
    - org.qbittorrent.qBittorrent
    - io.github.martinrotter.rssguardlite
    - org.nicotine_plus.Nicotine

    # chat
    - org.gajim.Gajim
    - in.cinny.Cinny
    - chat.revolt.RevoltDesktop
    - org.signal.Signal
    - dev.vencord.Vesktop

    # gaming
    - org.libretro.RetroArch
    - org.DolphinEmu.dolphin-emu
    - net.pcsx2.PCSX2
    - org.duckstation.DuckStation
    - org.ppsspp.PPSSPP
    - net.kuribo64.melonDS
    - io.github.dosbox-staging
    - org.freedesktop.Platform.VulkanLayer.gamescope//23.08
    - org.freedesktop.Platform.VulkanLayer.MangoHud//23.08
    - org.prismlauncher.PrismLauncher

    # utilities
    - io.gitlab.azymohliad.WatchMate
    - org.gimp.GIMP
    - org.kde.krita
    - org.kde.kdenlive
