type: rpm-ostree
repos:
  # starship prompt
  - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo

  # hblock
  - https://copr.fedorainfracloud.org/coprs/pesader/hblock/repo/fedora-%OS_VERSION%/pesader-hblock-fedora-%OS_VERSION%.repo

  # wezterm terminal
  - https://copr.fedorainfracloud.org/coprs/wezfurlong/wezterm-nightly/repo/fedora-%OS_VERSION%/wezfurlong-wezterm-nightly-fedora-%OS_VERSION%.repo
install:
  # environment
  - pavucontrol-qt
  - playerctl
  - mpv
  - waydroid
  - crontabs
  - gamemode
  - gamescope
  - mangohud
  - hblock

  # themes
  - papirus-icon-theme

  # material you colors dependencies
  - python3-dbus
  - python3-numpy

  # joystickwake dependencies
  - python3-pyudev

  # terminals and console utilities
  - wezterm
  - kitty
  - bat
  - duf
  - fastfetch
  - fd-find
  - fzf
  - git-delta
  - lsd
  - neovim
  - ripgrep
  - sd
  - starship
  - zoxide
  - zsh

  # kde utilities
  - ark
  - dolphin-plugins
  - kate
  - ksystemlog
  - ffmpegthumbs
  - kaccounts-integration
  - kaccounts-providers
  - kdepim
  - kdepim-addons
  - qt5-qtgraphicaleffects
  - qt5-qtquickcontrols2
  - qt5-qtsvg
  - translate-shell
  - power-profiles-daemon
  - plasma-sdk

  # libraries and tools
  - fontconfig
  - gnome-themes-extra
  - lzip
  - qt5-qtwayland
  - qt6-qtwayland
remove:
  - firefox # default firefox removed in favor of flatpak
  - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
