type: rpm-ostree
repos:
  # starship prompt
  - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo

  # hblock
  - https://copr.fedorainfracloud.org/coprs/pesader/hblock/repo/fedora-%OS_VERSION%/pesader-hblock-fedora-%OS_VERSION%.repo

  # wezterm terminal
  - https://copr.fedorainfracloud.org/coprs/wezfurlong/wezterm-nightly/repo/fedora-%OS_VERSION%/wezfurlong-wezterm-nightly-fedora-%OS_VERSION%.repo

  # waydroid (custom builds to fix minor issues)
  - https://copr.fedorainfracloud.org/coprs/huakim/waydroid/repo/fedora-%OS_VERSION%/huakim-waydroid-fedora-%OS_VERSION%.repo
install:
  # environment
  - pavucontrol-qt
  - playerctl
  - mpv
  - crontabs
  - gamemode
  - gamescope
  - mangohud
  - hblock
  - nextcloud-client
  - nextcloud-client-dolphin

  # themes
  - papirus-icon-theme
  - oxygen-sounds
  - plasma-mobile-sounds
  - pop-sound-theme
  - yaru-sound-theme
  - deepin-sound-theme

  # joystickwake dependencies
  - python3-pyudev

  # virt-manager
  - qemu
  - qemu-user-binfmt
  - virt-manager
  - libvirt
  - edk2-ovmf
  - genisoimage
  - qemu-img
  - qemu-system-x86-core
  - qemu-char-spice
  - qemu-device-usb-redirect
  - qemu-device-display-virtio-vga
  - qemu-device-display-virtio-gpu

  # waydroid
  - waydroid
  - waydroid-image-system-vanilla

  # mpd
  - mpd
  - mpdris2
  - ncmpcpp

  # terminals and console utilities
  - wezterm
  - kitty
  - bat
  - duf
  - fastfetch
  - fd-find
  - fzf
  - git-delta
  - lsd
  - neovim
  - ripgrep
  - sd
  - starship
  - zoxide
  - zsh

  # kde utilities
  - ark
  - dolphin-plugins
  - kate
  - ksystemlog
  - ffmpegthumbs
  - kaccounts-integration
  - kaccounts-providers
  - kdepim
  - kdepim-addons
  - qt6-qtquickcontrols2
  - qt6-qtsvg
  - translate-shell
  - power-profiles-daemon
  - plasma-sdk

  # libraries and tools
  - fontconfig
  - gnome-themes-extra
  - lzip
  - qt5-qtwayland
  - qt6-qtwayland
remove:
  - firefox # default firefox removed in favor of flatpak
  - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
