type: default-flatpaks
notify: true
system:
  repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
  repo-name: flathub
  repo-title: "Flathub (system-wide)"
  install:
    # internet
    - org.mozilla.firefox
    - org.mozilla.Thunderbird

    # office
    - org.libreoffice.LibreOffice
    - md.obsidian.Obsidian

    # utilities
    - fr.handbrake.ghb
    - org.kde.okteta
    - it.mijorus.smile

    # system applications
    - org.gnome.Loupe
    - org.gnome.gedit
    - org.gnome.clocks
    - org.gnome.Calculator
    - org.gnome.Evince
    - io.github.amit9838.mousam
    - org.gnome.Cheese
    - org.kde.filelight
    - io.github.cboxdoerfer.FSearch
    - org.pipewire.Helvum
    - org.gnome.DejaDup
    - com.github.tchx84.Flatseal
    - org.gustavoperedo.FontDownloader
    - com.mattjakeman.ExtensionManager
    - app.drey.Dialect
    - io.github.thetumultuousunicornofdarkness.cpu-x
user:
  repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
  repo-name: flathub-user
  repo-title: "Flathub (User)"
  install:
    # internet
    - org.qbittorrent.qBittorrent
    - io.gitlab.news_flash.NewsFlash
    - org.nicotine_plus.Nicotine

    # chat
    - org.gajim.Gajim
    - in.cinny.Cinny
    - chat.revolt.RevoltDesktop
    - org.signal.Signal
    - dev.vencord.Vesktop

    # gaming
    - org.DolphinEmu.dolphin-emu
    - io.github.dosbox-staging
    - org.prismlauncher.PrismLauncher
    - net.davidotek.pupgui2
    - org.libretro.RetroArch

    # utilities
    - com.bitwarden.desktop
    - com.usebottles.bottles
    - io.github.mpobaschnig.Vaults
    - io.github.seadve.Mousai
    - io.gitlab.azymohliad.WatchMate
