type: rpm-ostree
remove:
# default sericea packages, removing most we can of sway without removing other "important"/system packages
    - sway
    - swaybg
    - swayidle
    - swaylock
    - sway-systemd
    - foot
    - rofi-wayland
    - lxqt-policykit
