type: rpm-ostree
repos:
    # starship prompt
    - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo

    # wezterm
    - https://copr.fedorainfracloud.org/coprs/wezfurlong/wezterm-nightly/repo/fedora-%OS_VERSION%/wezfurlong-wezterm-nightly-fedora-%OS_VERSION%.repo
install:
    # environment
    - pavucontrol
    - playerctl
    - qt5-qtwayland
    - qt6-qtwayland
    - google-noto-emoji-fonts
    - power-profiles-daemon
    - upower
    - powertop
    - gamemode
    - gamescope
    - mangohud
    - waydroid
    - mpv

    # sound
    - pamixer

    # file management things
    - udiskie
    - p7zip
    - unrar-free

    # terminal & utilities
    - wezterm
    - bat
    - duf
    - fastfetch
    - fd-find
    - fzf
    - git-delta
    - lsd
    - neovim
    - ripgrep
    - sd
    - starship
    - zoxide
    - zsh
    - fontconfig
    - crontabs

    # gnome extensions
    - gnome-shell-extension-forge
    - gnome-shell-extension-openweather
    - gnome-shell-extension-appindicator
    - gnome-shell-extension-gsconnect
    - gnome-shell-extension-gamemode
    - gnome-shell-extension-blur-my-shell
    - gnome-shell-extension-just-perfection
    - gnome-shell-extension-dash-to-dock

    # themes and GUI
    - papirus-icon-theme
    - qt5ct
    - qt6ct
    - kvantum
    - gnome-themes-extra
remove:
    - firefox # default firefox removed in favor of flatpak
    - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
    - gnome-initial-setup # Causes issues for some reason(?)
    - gnome-classic-session
    - gnome-software-rpm-ostree
    - gnome-terminal
    - gnome-terminal-nautilus
    - gnome-tweaks
