type: rpm-ostree
repos:
    # starship prompt
    - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo

    # wezterm
    - https://copr.fedorainfracloud.org/coprs/wezfurlong/wezterm-nightly/repo/fedora-%OS_VERSION%/wezfurlong-wezterm-nightly-fedora-%OS_VERSION%.repo
install:
    # environment
    - brightnessctl
    - pavucontrol
    - playerctl
    - qt6-qtwayland
    - google-noto-emoji-fonts
    - power-profiles-daemon
    - powertop
    - gamescope
    - mangohud
    - waydroid
    - mpv
    - nextcloud-client
    - gpaste
    - libgda
    - libgda-sqlite
    - jq
    - xprop

    # file management things
    - udiskie
    - p7zip
    - unrar-free

    # terminal & utilities
    - wezterm
    - bat
    - duf
    - fastfetch
    - fd-find
    - fzf
    - git-delta
    - lsd
    - neovim
    - ripgrep
    - sd
    - starship
    - zoxide
    - zsh
    - crontabs

    # gnome extensions
    - lm_sensors
    - libgtop2-devel
    - gnome-shell-extension-forge
    - gnome-shell-extension-openweather
    - gnome-shell-extension-appindicator
    - gnome-shell-extension-gsconnect
    - gnome-shell-extension-blur-my-shell
    - gnome-shell-extension-just-perfection
    - gnome-shell-extension-dash-to-dock
    - gnome-shell-extension-user-theme
    #- gnome-shell-extension-unite

    # themes and GUI
    - papirus-icon-theme
    - qt5ct
    - qt6ct
remove:
    - firefox
    - firefox-langpacks
    - gnome-classic-session
    - gnome-software-rpm-ostree
    #- gnome-terminal
    #- gnome-terminal-nautilus
