type: rpm-ostree
repos:
    # starship prompt
    - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo

    # wezterm
    - https://copr.fedorainfracloud.org/coprs/wezfurlong/wezterm-nightly/repo/fedora-%OS_VERSION%/wezfurlong-wezterm-nightly-fedora-%OS_VERSION%.repo

    # rom properties
    - https://copr.fedorainfracloud.org/coprs/kylegospo/rom-properties/repo/fedora-%OS_VERSION%/kylegospo-rom-properties-fedora-%OS_VERSION%.repo
install:
# environment
    - xorg-x11-server-Xwayland
    - xdg-user-dirs
    - xsettingsd
    - dbus-tools
    - dbus-daemon
    - wl-clipboard
    - pavucontrol
    - playerctl
    - qt5-qtwayland
    - qt6-qtwayland
    - vulkan-validation-layers
    - vulkan-tools
    - google-noto-emoji-fonts
    - gnome-disk-utility
    - power-profiles-daemon
    - upower
    - powertop
    - gamemode
    - gamescope
    - mangohud

# sound
    - pamixer

# file manager
    - rom-properties-gtk3
    - udiskie
    - p7zip
    - unrar-free

# terminal & utilities
    - wezterm
    - bat
    - duf
    - fastfetch
    - fd-find
    - fzf
    - git-delta
    - lsd
    - neovim
    - ripgrep
    - sd
    - starship
    - zoxide
    - zsh
    - fontconfig
    - crontabs

# podman
    - podman
    - podman-compose
    - podman-tui

# media player
    - mpv

# themes and GUI
    - papirus-icon-theme
    - qt5ct
    - qt6ct
    - kvantum
    - gnome-themes-extra
