#!/usr/bin/env bash

# Tell this script to exit if there are any errors.
# You should have this in every custom script, to ensure that your completed
# builds actually ran successfully without any errors!
set -oue pipefail

# Theme names and stuff
GTK_THEME=Catppuccin-Mocha-Compact-Green-Dark

# Ensure directories exist
mkdir -p $HOME/.local/share/themes
mkdir -p $HOME/.local/share/icons

# Force copy system copies of themes to user dir
cp -rf /etc/skel/.local/share/themes/${GTK_THEME} $HOME/.local/share/themes
cp -rf /etc/skel/.local/share/themes/${GTK_THEME}-hdpi $HOME/.local/share/themes
cp -rf /etc/skel/.local/share/themes/${GTK_THEME}-xhdpi $HOME/.local/share/themes

# Create symlinks
ln -s $HOME/.local/share/themes $HOME/.themes
ln -s $HOME/.local/share/icons $HOME/.icons

