#!/usr/bin/env bash

# Tell this script to exit if there are any errors.
# You should have this in every custom script, to ensure that your completed
# builds actually ran successfully without any errors!
set -oue pipefail

# Theme names and stuff
GTK_THEME=Catppuccin-Mocha-Compact-Green-Dark
ICON_THEME=Papirus-Dark
CURSOR_THEME=Bibata-Modern-Mocha-Light

# Ensure directories exist
mkdir -p $HOME/.local/share/themes
mkdir -p $HOME/.local/share/icons
mkdir -p $HOME/.themes
mkdir -p $HOME/.icons

# Force copy system copies of themes to user dir
cp -rf /etc/skel/.local/share/themes/${GTK_THEME} $HOME/.local/share/themes
cp -rf /etc/skel/.local/share/themes/${GTK_THEME}-hdpi $HOME/.local/share/themes
cp -rf /etc/skel/.local/share/themes/${GTK_THEME}-xhdpi $HOME/.local/share/themes
cp -rf /etc/skel/.local/share/icons/${ICON_THEME} $HOME/.local/share/icons
cp -rf /etc/skel/.local/share/icons/${CURSOR_THEME} $HOME/.local/share/icons

# Create symlinks
ln -s $HOME/.local/share/themes/${GTK_THEME} $HOME/.themes
ln -s $HOME/.local/share/themes/${GTK_THEME}-hdpi $HOME/.themes
ln -s $HOME/.local/share/themes/${GTK_THEME}-xhdpi $HOME/.themes
ln -s $HOME/.local/share/icons/${ICON_THEME} $HOME/.icons
ln -s $HOME/.local/share/icons/${CURSOR_THEME} $HOME/.icons
