#!/usr/bin/env bash

img=$(find "/etc/mazurek/assets" -type f -print0 | shuf -z -n 1)

zenity --info --width=400 --icon="face-smile-big" --title="Welcome to Mazurek" --text="These windows will give you the basic information on how to navigate around your system.\n\nPlease do remember that this is a <i>completely personalized</i> for the images' creator, and that most things here are also things that either aren't compatible with your system/setup or things you just do not want.\n\nYou can find the <a href='https://git.gay/sneexy/el-dotfiles'>same exact dotfiles used here</a> over in its respective repository."

zenity --info --width=400 --icon="input-keyboard" --title="Hyprland Keybinds" --text="<b>⊞ Super + Q</b> • Quit/Close active window\n<b>⊞ Super + Shift + V</b> • Toggles window floating\n<b>⊞ Super + F</b> • Toggles fullscreen\n<b>⊞ Super + Space</b> • Opens application launcher\n<b>⊞ Super + C</b> • Open color picker\n<b>⊞ Super + Period</b> • Opens emoji picker\n<b>⊞ Super + V</b> • Shows clipboard history\n<b>⊞ Super + F12</b> • Toggles \"Focus mode\"\n<b>Control + Alt + Escape</b> • Toggles \"kill mode\"\n\n<b>⊞ Super + 1-0</b> • Switch workspaces\n<b>⊞ Super + Control + 1-0</b> • Move windows to workspaces\n\nMedia/Volume keys act as they should."

zenity --info --width=400 --icon="input-keyboard" --title="Application Keybinds" --text="<b>⊞ Super + Enter</b> • Opens a terminal\n<b>⊞ Super + Control + F</b> • Opens a file manager window\n<b>⊞ Super + Control + B</b> • Opens Firefox web browser\n<b>⊞ Super + Control + E</b> • Opens Thunderbird email\n<b>⊞ Super + Control + P</b> • Opens Bitwarden\n\n<b>⊞ Super + N</b> • Opens notification panel"

zenity --info --width=400 --title="More info" --text="For a more \"complete\" experience, you can run:\n\n<b>just mazurek-post-setup</b>\n\nin a terminal to finish setting more things up.\n\nMore recommended towards users who just installed Mazurek, but also for users who have rebased from another image if you haven't touched too much with your install."

zenity --info --width=400 --icon="$img" --ok-label="OK • mrrp meow :3 • rraawr x3" --title="That's all" --text="To see these messages again, run the script located at <b>/etc/mazurek/mazurek-first-time-messages.sh</b>.\n\n<a href='https://github.com/sernik-tech/member-images'>Sernik member-images repository</a>\n\nBy clicking the button below, you <b>100% fully agree</b> to trans rights, becoming a boy\/menkisser, owning at least 73 cats, snuggling your local dragons, destroying capitalism and eating your enemies.\n\n<small>Icon credits to <a href='https://www.ahnik.art/'>Ahnik</a></small>"
