id = 1165747824231723149

[format]
details = "$title"
state = "$artist - $album"
timestamp = "elapsed"
large_image = "blobcatheadphones"
small_image = "blobfoxheadphones"
large_text = "$album by $artist"
small_text = "i love music"
